steps:
  # Step 1: Install dependencies (if needed)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r /workspace/requirements.txt

  # Step 2: Deploy Cloud Function using the source from the repo
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'get_resume'
      - '--runtime'
      - 'python39'
      - '--trigger-http'
      - '--entry-point'
      - 'get_resume'
      - '--region'
      - 'us-east4'  # Ensure this region is allowed for your project
      - '--source'
      - '/workspace'  # Specify the source directory correctly
      - '--memory'
      - '256MB'
      - '--set-env-vars'
      - 'FIRESTORE_PROJECT=gcp-resume-challenge-083124'
      - '--service-account'
      - 'gcp-resume-challenge-083124@appspot.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY  # Ensure logs are sent to Cloud Logging

timeout: 1200s
