steps:
  # Step 1: Clone the repository from GitHub
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/smithddevon/gcpresume-challenge .
        cd gcpresume-challenge
        
  # Step 2: Install dependencies (if needed)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  # Step 3: Deploy Cloud Function using the source from the repo
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'get_resume'
      - '--runtime'
      - 'python39'
      - '--trigger-http'
      - '--entry-point'
      - 'get_resume'
      - '--region'
      - 'us-east4'
      - '--source'
      - '.'  # This indicates the current directory after cloning
      - '--memory'
      - '256MB'
      - '--set-env-vars'
      - 'FIRESTORE_PROJECT=gcp-resume-challenge-083124'
      - '--service-account'
      - 'gcp-resume-challenge-083124@appspot.gserviceaccount.com'
# Set logging options
options:
  logging: CLOUD_LOGGING_ONLY 

timeout: 1200s
