steps:
  # Step 1: Install Terraform (use a Docker image with Terraform pre-installed)
  - name: 'hashicorp/terraform:light'
    id: 'Terraform Init'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        terraform init -v

  # Step 2: Terraform plan
  - name: 'hashicorp/terraform:light'
    id: 'Terraform Plan'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        terraform plan -out=tfplan -v

  # Step 3: Apply Terraform (automated with -auto-approve flag)
  - name: 'hashicorp/terraform:light'
    id: 'Terraform Apply'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve tfplan -v

  # Step 4: Deploy Cloud Function (if required, assuming this step is automated separately)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Cloud Function'
    args: ['functions', 'deploy', 'get_resume', '--runtime', 'python39', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'get_resume']

  # Step 5: Additional steps as needed (optional)

timeout: '1200s'  # Increase the timeout as Terraform apply might take time

options:
  logging: CLOUD_LOGGING_ONLY